# Generated by Django 3.2.4 on 2021-07-31 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Category')),
                ('title', models.CharField(choices=[('', 'choose category'), ('goat', 'goat'), ('cow', 'cow'), ('cow', 'cow')], max_length=150, verbose_name='Category Title')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('livestock_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Livestock id')),
                ('livestock_name', models.CharField(max_length=244, verbose_name='Livestock name')),
                ('gender', models.CharField(choices=[('', 'choose gender'), ('male', 'male'), ('female', 'female')], max_length=255, verbose_name='Animal Gender')),
                ('status', models.CharField(choices=[('', 'choose status'), ('sold', 'sold'), ('active', 'active'), ('dead', 'dead')], max_length=255)),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('location', models.CharField(max_length=244, null=True)),
                ('weight', models.PositiveIntegerField(null=True)),
                ('ls_image', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Cattle Images')),
                ('color', models.CharField(blank=True, max_length=244, null=True)),
                ('horns', models.CharField(blank=True, max_length=244, null=True)),
                ('breed', models.CharField(blank=True, max_length=244, null=True)),
                ('cartegory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wanyama.category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Report id')),
                ('printed_report', models.FileField(upload_to='media/printedRiports', verbose_name='Erliar Printed')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Tag id')),
                ('tag', models.ImageField(blank=True, null=True, upload_to='media/tags', verbose_name='Image Tag')),
                ('tag_type', models.CharField(default='QR-code', max_length=255, verbose_name='Tag Type')),
                ('livestock', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wanyama.livestock')),
            ],
        ),
        migrations.CreateModel(
            name='Livestock_Health',
            fields=[
                ('livestok_heath_id', models.AutoField(primary_key=True, serialize=False)),
                ('disability', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], max_length=255, verbose_name='Has Disability?')),
                ('medication', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], max_length=255, verbose_name='Takes Drugs?')),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Explanations')),
                ('health', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wanyama.livestock', verbose_name='Health Status')),
            ],
            options={
                'verbose_name_plural': 'Health',
            },
        ),
        migrations.CreateModel(
            name='ExpenseIncome',
            fields=[
                ('ei_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount')),
                ('descriptions', models.TextField(max_length=255, verbose_name='Due to ')),
                ('ei_type', models.CharField(choices=[('', 'choose source'), ('SALES', 'Sales'), ('PURCHASES', 'Purchases'), ('OTHERS', 'Others')], max_length=250, verbose_name='Source')),
                ('due_date', models.DateField(verbose_name='Due date')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer')),
            ],
            options={
                'verbose_name_plural': 'Expenses and Incomes',
            },
        ),
    ]
